#http://docs.travis-ci.com/user/languages/r/

language: r
sudo: required

warnings_are_errors: false

apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev
 
r_binary_packages:
 - magrittr
 - dplyr
 - maps
 - ggplot2

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
